app/controllers/DefaultController.php
<?php

/**
 * Home controller
 * @author Fred<mconyango@gmail.com>
 */
class DefaultController extends Controller {

    public function init() {
        parent::init();
    }

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users
                'actions' => array('firststep','invoicetest', 'header', 'headerlib', 'dashboard', 'sidebar', 'footer', 'orderpage',
                    'pagehead', 'registration', 'createmember', 'pricedetails',
                    'writersregistration', 'contactus', 'savecontactus','current'),
                'users' => array('*'),
            ),
            array('allow',
                'actions' => array('index', 'uploads', '_reportCSV',
                    'messages', 'messagesreplied', 'messagereplydelete',
                    'messagesreply', 'messagedelete'),
                'users' => array('@'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Declares class-based actions.
     */
    public function actions() {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha' => array(
                'class' => 'CCaptchaAction',
                'backColor' => 0xFFFFFF,
            ),
            // page action renders "static" pages stored under 'protected/views/site/pages'
            // They can be accessed via: index.php?r=site/page&view=FileName
            'page' => array(
                'class' => 'CViewAction',
            ),
        );
    }

    public function actionHeader() {
        $this->renderPartial('tpl/header');
    }

    public function actionHeaderlib() {
        $this->renderPartial('tpl/headerlib');
    }

    public function actionLib() {
        $this->renderPartial('tpl/lib');
    }

    public function actionDashboard() {
        //$model = new Orders();

        $this->render('dashboard');
        // $this->renderPartial('dashboard');
    }
     public function actionCurrent() {
        //$model = new Orders();

        $this->render('current');
        // $this->renderPartial('dashboard');
    }

    public function actionCreatemember() {

        $model = new Membership();
        if (isset($_POST['fname']) && isset($_POST['lname']) && isset($_POST['email']) && isset($_POST['mobile'])) {
            $model->fname = $_POST['fname'];
            $model->lname = $_POST['lname'];
            $model->email = $_POST['email'];
            $model->mobile = $_POST['mobile'];
            $model->dob = $_POST['dob'];

            if ($model->save()) {//start saving on the user end
                // $model->membership_code = $model->member_id < 10 ? 'UBS0' . $model->member_id : 'UBS' . $model->member_id;
                $model->save();
                $usermodel = new Users(ActiveRecord::SCENARIO_CREATE);
                $usermodel->name = $model->fname . " " . $model->lname;
                $usermodel->username = $_POST['email'];
                $usermodel->email = $model->email;
                $usermodel->phone = $model->mobile;
                $salt = Common::generateSalt();
                // $usermodel->setScenario(Users::SCENARIO_UPDATE);
                $usermodel->password = $salt . md5($_POST['password']);
                // var_dump($usermodel->password);
                $usermodel->salt = $salt;
                $usermodel->user_level = 3;
                $usermodel->role_id = 3;
                $error_message = CActiveForm::validate($usermodel);
                $error_message_decoded = json_decode($error_message);
                if (empty($error_message_decoded)) {
                    $usermodel->save();
                    $usermodel->password = $salt . md5($_POST['password']);
                    $usermodel->salt = $salt;
                    $usermodel->save();

                    $model->user_id = $usermodel->id;
                    $model->save();
// the message
                    $msg = "Thank you for Registering to Become a member of Ubunifu Sacco. Your Login Email is  " . $usermodel->username . ", Password is " . $_POST['password'] . ". Kindly Login using this Link http://dash.ubunifusacco.com/auth/default/login";
                    //get all emails to send to rem the first one is the registrant
                    $msg = wordwrap($msg, 70);
                    mail($usermodel->email, "Welcome to Ubunifu Sacco, Ready to transform your Future through Savings", $msg);
                    $adminemails = Emails::model()->findAll(array('condition' => "email_category=1"));
                    $adminmsg = "A new Member has Just Registered and has email " . $usermodel->email . ". "
                            . "Kindly Login and Check his Profile. "
                            . "Also advise the New Member to complete His/ Her Registration Profile";
                    $adminmsg = wordwrap($adminmsg, 70);
                    foreach ($adminemails as $emails) {
                        mail($emails->email, "New Member Code:  " . $model->membership_code, $adminmsg);
                    }


                    echo json_encode(array('operation' => "success"));
                } else {
                    $errorlist = "<br />";
                    foreach ($error_message_decoded as $error) {
                        $errorlist.=$error[0] . '<br />';
                    }
                    //echo $error_message_decoded;
                    echo json_encode(array("operation" => "error", "the_errors" => $errorlist));
                    // $this->redirect('registration/index',array('model'=>$model));
                }



                //Yii::app()->user->Flash()
            }
        }




        //   echo "more..";
        //  exit;
        else {
            $this->render('registration/index', array('model' => $model));
        }
    }

    public function actionSidebar() {
        $this->renderPartial('tpl/sidebar');
    }

    public function actionFooter() {
        $this->renderPartial('tpl/footer');
    }
    
    public function actionInvoicetest() {
        echo $this->renderPartial('application.views.default.tpl.headerlib');
        $email="kimoduor";
        $itemname="NEW oRDER";
        $descript="The new Order";
        $amount="90";        
        Invoice::showinvoice($email, $itemname, $descript, $amount);
            }

    public function actionPagehead() {
        $this->renderPartial('tpl/pagehead');
    }

    public function actionRegistration() {
        $model = new Orders();

        $this->render('registration/index', array('model' => $model));
    }

    public function actionWritersregistration() {
        $this->render('registration/writersregistration');
    }

    public function actionContactus() {
        $this->render('registration/contactus');
    }

    public function actionOrderpage() {
        $this->render('tpl/orderpage');
    }

    public function actionSavecontactus() {//make sure you send email to all the admins
        if (isset($_POST['email'])) {
            $email = $_POST['email'];
            $message = $_POST['message'];
            //send email to those whose role is 2
            $usermodels = Users::model()->findAll('role_id=2');
            foreach ($usermodels as $usermodel) {
                Common::sendEmail($usermodel->email, $email, "$email via Contact us", $message);
                $notificationmodel = new Notifications();
                $notificationmodel->touser_id = $usermodel->id;
                $notificationmodel->subject = "$email via Contact us";
                $notificationmodel->body = $message;
                // var_dump($notificationmodel);                
                $notificationmodel->save();
            }
            echo true;
        }
        echo true;
    }

    /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
     */
    public function actionIndex() {
        $this->pageTitle = Lang::t('Dashboard');
        $this->activeMenu = 1;


        $this->render('index', array(
        ));
    }

    public function actionPricedetails() {
        $model = Prices::model()->loadModel(1);
        $levelrate = 0;
        $papertyperate = 0;
        $timeframerate = 0;
        if (isset($_POST['level_id']) && $_POST['level_id'] > 0) {
            $levelmodel = Levels::model()->loadModel($_POST['level_id']);
            $levelrate = $levelmodel->rate;
        }
        if (isset($_POST['papertype_id']) && $_POST['papertype_id'] > 0) {
            $papertypemodel = Papertypes::model()->loadModel($_POST['papertype_id']);
            $papertyperate = $papertypemodel->rate;
        }
        if (isset($_POST['timeframe_id']) && $_POST['timeframe_id'] > 0) {
            $timeframemodel = Timeframe::model()->loadModel($_POST['timeframe_id']);
            $timeframerate = $timeframemodel->rate;
        }
        $array = array();
        $array['minimumcpp'] = $model->minimumcpp;
        $array['amountperword'] = $model->amountperword;
        $array['papertyperate'] = $papertyperate;
        $array['levelrate'] = $levelrate;
        $array['timeframerate'] = $timeframerate;
        $theoutput = json_encode($array);
        echo $theoutput;
    }

}

app/views/default/tpl/footer.php
<div class="page-footer-inner">
	<?php echo date("Y");?> &copy; Geek  Writers
</div>
<div class="scroll-to-top" style="float: right;margin-right: 0;">
	<i class="icon-arrow-up"></i>
</div>
 <script src="<?php echo Yii::app()->baseUrl; ?>/malt/assets/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
        <script src="<?php echo Yii::app()->baseUrl; ?>/malt/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="<?php echo Yii::app()->baseUrl; ?>/malt/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
        <script src="<?php echo Yii::app()->baseUrl; ?>/malt/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
        <script src="<?php echo Yii::app()->baseUrl; ?>/malt/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
        <script src="<?php echo Yii::app()->baseUrl; ?>/malt/assets/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
        <script src="<?php echo Yii::app()->baseUrl; ?>/malt/assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
        <!-- END CORE JQUERY PLUGINS -->

app/views/default/tpl/headerlib.php
<!DOCTYPE html>
<html lang="en" data-ng-app="MuskeyApp">
    <!--<![endif]-->
    <!-- BEGIN HEAD -->
    <head>
        <title data-ng-bind="'Votex| ' + $state.current.data.pageTitle"></title>

        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport"/>
        <meta content="" name="description"/>
        <meta content="" name="author"/>
        <!-- BEGIN HEADER INNER -->
        <script src="<?php echo Yii::app()->baseUrl . '/malt/assets/registration/js/jquery-1.10.2.js'; ?>"></script>
        <script src="<?php echo Yii::app()->baseUrl . '/malt/assets/registration/js/jquery-ui.js'; ?>"></script>


        <link rel="stylesheet" href="<?php echo Yii::app()->baseUrl . '/malt/assets/registration/css/main.css'; ?>">
        <link rel="stylesheet" href="<?php echo Yii::app()->baseUrl . '/malt/assets/registration/css/sky-forms.css'; ?>">
        <link rel="stylesheet" href="<?php echo Yii::app()->baseUrl . '/malt/assets/registration/css/jquery-ui.css'; ?>">
       <script src="<?php echo Yii::app()->baseUrl . '/malt/assets/registration/js/moment.js'; ?>"></script>

        <!-- BEGIN GLOBAL MANDATORY STYLES -->
        <link href="<?php echo Yii::app()->baseUrl; ?>/malt/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo Yii::app()->baseUrl; ?>/malt/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo Yii::app()->baseUrl; ?>/malt/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo Yii::app()->baseUrl; ?>/malt/assets/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>


        <!-- END GLOBAL MANDATORY STYLES -->

        <!-- BEGIN DYMANICLY LOADED CSS FILES(all plugin and page related styles must be loaded between GLOBAL and THEME css files ) -->
        <link id="ng_load_plugins_before"/>
        <!-- END DYMANICLY LOADED CSS FILES -->

        <!-- BEGIN THEME STYLES -->
        <!-- DOC: To use 'rounded corners' style just load 'components-rounded.css' stylesheet instead of 'components.css' in the below style tag -->
        <link href="<?php echo Yii::app()->baseUrl; ?>/malt/assets/global/css/components-rounded.css" id="style_components" rel="stylesheet" type="text/css"/>
        <link href="<?php echo Yii::app()->baseUrl; ?>/malt/assets/global/css/plugins.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo Yii::app()->baseUrl; ?>/malt/assets/admin/layout4/css/layout.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo Yii::app()->baseUrl; ?>/malt/assets/admin/layout4/css/themes/light.css" rel="stylesheet" type="text/css" id="style_color"/>
        <link href="<?php echo Yii::app()->baseUrl; ?>/malt/assets/admin/layout4/css/custom.css" rel="stylesheet" type="text/css"/>
        <script type="text/ecmascript" src="<?php echo Yii::app()->baseUrl; ?>/malt/jqgrid/js/grid.locale-en.js"></script> 
        <script type="text/ecmascript" src="<?php echo Yii::app()->baseUrl; ?>/malt/jqgrid/js/jquery.jqGrid.js"></script>
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo Yii::app()->baseUrl; ?>/malt/jqgrid/css/ui.jqgrid-bootstrap.css" />

app/views/default/tpl/orderpage.php
<?php $model = new Orders(); ?>
<style>

    .errordisplay{
        background-color:#fef4ef;
        border:1px solid #f56709;
        position:absolute;
        width:28.2%;
        padding: 10px;
        top: 20px;
        color:red;
        z-index:100;

    }.error{
        background-color:#fef4ef;
        border:1px solid #f56709;
        position:absolute;
        width:28.2%;
        padding: 10px;
        top: 90px;
        color:red;
        font-size: 13px;
        z-index:100;
        box-shadow: 1px #fef4ef;
        border-radius: 3px;

    }
    .success{
        background-color:#ccffcc;
        border:1px solid green;
        position:absolute;
        width:28.2%;
        padding: 10px;
        top: 90px;
        font-size: 13px;
        z-index:100;
        box-shadow: 1px #ccffcc;
        border-radius: 3px;
    }
    .loading{
        opacity:0.4;
    }

</style>
    <div class="col-md-12 sky-form"  id="sky-form">
            <fieldset>
                <form action="<?php echo Yii::app()->baseUrl . '/orders/orders/create'; ?>" method="post"  enctype="multipart/form-data">
                    <div class="row fm">

                        <div class="col-md-4"> Email </div> 
                        <div class="col-md-8"> <label class="input">
                                <i class="icon-append fa-envelope-o"></i>
                                <input type="email" name="email" id="email" class="form-control" placeholder="Email address">
                                <b class="tooltip tooltip-bottom-right">Enter Email to verify your account</b>
                            </label>
                        </div>
                    </div>
                    <div class="row fm">
                        <div class="col-md-4"> Type of Paper </div> 
                        <div class="col-md-8">
                            <label class="input">
                                <i class="icon-append "></i>
                                <?php echo CHtml::activeDropDownList($model, 'papertype_id', Papertypes::model()->getListData('papertype_id', 'papertype'), array('class' => 'form-control', 'required' => true, 'onchange' => 'calculateamount()')); ?>
                                <b class="tooltip tooltip-bottom-right">Type of the Paper</b>
                            </label>
                        </div>
                    </div>
                    <div class="row fm">
                        <div class="col-md-4"> Topic of the Paper</div> 
                        <div class="col-md-8">
                            <label class="input">
                                <i class="icon-append fa-ils"></i>
                                <input type="text"  class="form-control" name="title" id="topic" placeholder="Topic">
                                <b class="tooltip tooltip-bottom-right">Topic of the Paper</b>
                            </label>
                        </div>
                    </div>
                    <div class="row fm">
                        <div class="col-md-4"> Number of Words</div> 
                        <div class="col-md-8">
                            <label class="input">
                                <i class="icon-append fa-h-square"></i>
                                <input type="number" onclick="calculateamount()" onkeyup="calculateamount()"  class="form-control" name="words" id="words" placeholder="Number of Words">
                                <b class="tooltip tooltip-bottom-right">Number of Words</b>                          
                            </label>
                        </div>
                    </div>
                    <div class="row fm">
                        <div class="col-md-4">Paper Level</div> 
                        <div class="col-md-8">
                            <label class="input">
                                <i class="icon-append"></i>
                                <?php echo CHtml::activeDropDownList($model, 'level_id', Levels::model()->getListData('level_id', 'level'), array('class' => 'form-control', 'required' => true, 'onchange' => 'calculateamount()')); ?>

                                <b class="tooltip tooltip-bottom-right">Paper Level</b>
                            </label>
                        </div>
                    </div>
                    <div class="row fm">
                        <div class="col-md-4">Deadline</div> 
                        <div class="col-md-8">
                            <label class="input">
                                <i class="icon-append fa-calendar"></i>
                                <input type="text" class="form-control" name="deadline" placeholder="Deadline" id="datepicker">
                                <b class="tooltip tooltip-bottom-right">Deadline</b>
                            </label>
                            <label>Time:</label> 
                            <input type="range" name="hours" min="0" max="23" value="0" oninput="this.form.amountInput.value=this.value" onchange="datedifference()" />
                            <input style="border:0; background: #f0f0f0; width: 29px; padding: 0" id="hrs" disabled="true" type="number" name="amountInput" min="0" max="23" value="0" oninput="this.form.amountRange.value=this.value" onchange="datedifference()" />.00  Hrs
                            <br /> <strong>[<span id="left"></span>  Left]</strong>

                        </div>
                    </div>

                    <div class="row fm">
                        <div class="col-md-4">Upload Additional Materials</div> 
                        <div class="col-md-8">
                            <label class="input">
                                <i class="icon-append fa-file"></i>
                                <?php
                                $this->widget('CMultiFileUpload', array(
                                    'model' => $model,
                                    'attribute' => 'Files',
                                    'name' => 'Files',
                                    'accept' => 'jpg|gif|png|doc|docx|txt|pdf|zip|rar|xls|xlsx|accdb|pub',
                                    'options' => array(
                                        'afterFileRemove' => 'function(e, v, m){ alert("Ready to Remove - "+v+"") }',
                                    ),
                                    'denied' => 'File is not allowed',
                                    'max' => 10, // max 10 files
                                ));
                                ?>
                            </label>
                        </div>
                    </div>
                    <footer> 
                        <label class="arrow_box" style="float: left;">$<span  id="amount">0</span></label>
                        <input type="hidden" id="amountfromclient" name="amountfromclient">
                        <button type="submit" class="button" id="submit">Continue ></button>
                        <img id="loader" style="display: none;" src="<?php echo Yii::app()->baseUrl ?>/malt/img/loader.gif">
                    </footer>
                </form>
            </fieldset>

</div>







<script>


    var dateToday = new Date();
    $(function() {
        $("#datepicker").datepicker({
            showButtonPanel: true,
            changeMonth: true,
            changeYear: true,
            minDate: dateToday,
            onSelect: function() {
                datedifference();
            },
            dateFormat: "yy-mm-dd"
        });
    });
    function datediffunc(mydate, myhrs) {
        if (mydate.length >= 4) {
            var date = new Date(mydate);
            var chosendate = (date.getMonth() + 1) + '/' + date.getDate() + '/' + date.getFullYear() + " " + myhrs + ":00:00";
            var now = new Date();
            var nowproper = (now.getMonth() + 1) + '/' + now.getDate() + '/' + now.getFullYear() + " " + now.getHours() + ":" + now.getMinutes();
            //----------------------------start the difference--------------------------
            var diff = moment.duration(moment(chosendate).diff(moment(nowproper)));
            var days = parseInt(diff.asDays()); //84
            var hours = parseInt(diff.asHours());
            hours = hours - days * 24; // 23 hours
            var minutes = parseInt(diff.asMinutes());
            minutes = minutes - (days * 24 * 60 + hours * 60);
            var outputstring = days + " Days " + hours + " Hours " + minutes + " Minutes";
            //calculateamount();
            return (days * 24) + hours;
            //----------------------------end the difference----------------------------
        }
    }
    function datedifference() {
        var mydate = $('#datepicker').val();
        var myhrs = $('#hrs').val();
        if (mydate.length >= 4) {
            var date = new Date(mydate);
            var chosendate = (date.getMonth() + 1) + '/' + date.getDate() + '/' + date.getFullYear() + " " + myhrs + ":00:00";
            var now = new Date();
            var nowproper = (now.getMonth() + 1) + '/' + now.getDate() + '/' + now.getFullYear() + " " + now.getHours() + ":" + now.getMinutes();
            //----------------------------start the difference--------------------------
            var diff = moment.duration(moment(chosendate).diff(moment(nowproper)));
            var days = parseInt(diff.asDays()); //84
            var hours = parseInt(diff.asHours());
            hours = hours - days * 24; // 23 hours
            var minutes = parseInt(diff.asMinutes());
            minutes = minutes - (days * 24 * 60 + hours * 60);
            var outputstring = days + " Days " + hours + " Hours " + minutes + " Minutes";
            $('#left').html(outputstring);
            calculateamount();

        }
    }

    function calculateamount() {
        var hoursleft = datediffunc($('#datepicker').val(), $('#hrs').val());
        $.ajax({'type': 'POST',
            'url': '<?php echo Yii::app()->baseUrl . '/default/pricedetails'; ?>',
            'cache': false,
            'data': {'level_id': $('#Orders_level_id').val(), 'papertype_id': $('#Orders_papertype_id').val(), 'hoursleft': hoursleft},
            'success': function(jsondetails) {
                var ojb = JSON.parse(jsondetails);
                var minimalcpp = parseFloat(ojb['minimumcpp']);
                var levelrate = parseFloat(ojb['levelrate']);
                var papertyperate = parseFloat(ojb['papertyperate']);
                var timeframerate = parseFloat(ojb['timeframerate']);
                var words = parseFloat($('#words').val());
                var wordsamount = parseFloat(words) * parseFloat(ojb['amountperword']);
                var level = wordsamount * levelrate;
                var papertype = wordsamount * papertyperate;
                var timeframerateamount = wordsamount * timeframerate;
                var amount = minimalcpp + wordsamount + level + papertype + timeframerateamount;
                $('#amount').html(Math.round(amount));
                  $('#amountfromclient').val(Math.round(amount));
            }
        });
    }
    $('#submit').click(function(event) {
        $('#loader').show();
        $('.body').addClass("loading");
        $(":text,#email,:password, select").each(function() {
            if ($(this).val() === "") {
                event.preventDefault();
                $(this).css("background-color", "#fef4ef");
                $(this).css("border", "1px solid #f56709");
                $('.body').removeClass("loading");
                $('#loader').hide();
            }
            else {
                $(this).css("background-color", "#fff");
                $(this).css("border", "2px solid #e5e5e5");
                
            }

        });
    });
</script>

app/views/default/tpl/pagehead.php
<!-- BEGIN PAGE TITLE -->
<div class="page-title">
    <h1><span data-ng-bind="$state.current.data.pageTitle"></span> <small data-ng-bind="$state.current.data.pageSubTitle"></small></h1>
</div> 



<!-- END PAGE TITLE -->
<!-- BEGIN PAGE TOOLBAR -->
<div class="page-toolbar">
    <!-- BEGIN THEME PANEL -->
    <div class="btn-group btn-theme-panel">
        <a href="javascript:;" class="btn dropdown-toggle" data-toggle="dropdown">
            <i class="icon-settings"></i>
        </a>
        <div class="dropdown-menu theme-panel pull-right dropdown-custom hold-on-click">
            <div class="row">
                <div class="col-md-4 col-sm-4 col-xs-12">
                    <h3>THEME</h3>
                    <ul class="theme-colors">
                        <li class="theme-color theme-color-default active" data-theme="default">
                            <span class="theme-color-view"></span>
                            <span class="theme-color-name">Dark Header</span>
                        </li>
                        <li class="theme-color theme-color-light" data-theme="light">
                            <span class="theme-color-view"></span>
                            <span class="theme-color-name">Light Header</span>
                        </li>
                    </ul>
                </div>
                <div class="col-md-8 col-sm-8 col-xs-12 seperator">
                    <h3>LAYOUT</h3>
                    <ul class="theme-settings">
                        <li>
                            Theme Style
                            <select class="layout-style-option form-control input-small input-sm">
                                <option value="square" selected="selected">Square corners</option>
                                <option value="rounded">Rounded corners</option>
                            </select>
                        </li>
                        <li>
                            Layout
                            <select class="layout-option form-control input-small input-sm">
                                <option value="fluid" selected="selected">Fluid</option>
                                <option value="boxed">Boxed</option>
                            </select>
                        </li>
                        <li>
                            Header
                            <select class="page-header-option form-control input-small input-sm">
                                <option value="fixed" selected="selected">Fixed</option>
                                <option value="default">Default</option>
                            </select>
                        </li>
                        <li>
                            Top Dropdowns
                            <select class="page-header-top-dropdown-style-option form-control input-small input-sm">
                                <option value="light">Light</option>
                                <option value="dark" selected="selected">Dark</option>
                            </select>
                        </li>
                        <li>
                            Sidebar Mode
                            <select class="sidebar-option form-control input-small input-sm">
                                <option value="fixed">Fixed</option>
                                <option value="default" selected="selected">Default</option>
                            </select>
                        </li>
                        <li>
                            Sidebar Menu
                            <select class="sidebar-menu-option form-control input-small input-sm">
                                <option value="accordion" selected="selected">Accordion</option>
                                <option value="hover">Hover</option>
                            </select>
                        </li>
                        <li>
                            Sidebar Position
                            <select class="sidebar-pos-option form-control input-small input-sm">
                                <option value="left" selected="selected">Left</option>
                                <option value="right">Right</option>
                            </select>
                        </li>
                        <li>
                            Footer
                            <select class="page-footer-option form-control input-small input-sm">
                                <option value="fixed">Fixed</option>
                                <option value="default" selected="selected">Default</option>
                            </select>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- END THEME PANEL -->
</div>
<!-- END PAGE TOOLBAR -->